export const skillCategories = [
  {
    id: "frontend",
    name: "Frontend Development",
    iconHref: "/skills/web-development.png",
    iconAlt: "Frontend Development icon",
    blurb: "Membangun antarmuka yang responsif, cepat, dan enak dipakai.",
    stack: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "ReactJs",
      "NextJs",
      "TailwindCSS",
      "Bootstrap",
    ],
  },
  {
    id: "restapi",
    name: "Rest API",
    iconHref: "/skills/rest-api.png",
    iconAlt: "Rest API icon",
    blurb: "Merancang dan mengonsumsi API yang rapi, aman, dan terdokumentasi.",
    stack: ["ExpressJs", "NodeJs", "Postman", "Firebase", "Supabase"],
  },
  {
    id: "backend",
    name: "Backend Development",
    iconHref: "/skills/backend.png",
    iconAlt: "Backend Development icon",
    blurb: "Mengelola logika server, database, dan skalabilitas sistem.",
    stack: [
      "NodeJs",
      "ExpressJs",
      "Golang",
      "PHP",
      "MySQL",
      "MongoDB",
      "Firebase",
      "Supabase",
    ],
  },
];
