export const skillCategories = [
  {
    id: "frontend",
    name: "Frontend Development",
    iconHref: "/skills/web-development.png",
    iconAlt: "Frontend Development icon",
    blurb: "Building responsive, fast, and user-friendly interfaces.",
    stack: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "ReactJs",
      "NextJs",
      "TailwindCSS",
      "Bootstrap",
    ],
  },
  {
    id: "restapi",
    name: "Rest API",
    iconHref: "/skills/rest-api.png",
    iconAlt: "Rest API icon",
    blurb: "Designing and consuming clean, secure, and well-documented APIs.",
    stack: ["ExpressJs", "NodeJs", "Postman", "Firebase", "Supabase"],
  },
  {
    id: "backend",
    name: "Backend Development",
    iconHref: "/skills/backend.png",
    iconAlt: "Backend Development icon",
    blurb: "Managing server logic, databases, and system scalability.",
    stack: [
      "NodeJs",
      "ExpressJs",
      "Golang",
      "MySQL",
      "MongoDB",
      "Firebase",
      "Supabase",
    ],
  },
];
